apiVersion: apps/v1
kind: Deployment
metadata:
  name: flags-2-env-api-server
  namespace: flags-2-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flags-2-env-api-server
  template:
    metadata:
      labels:
        app: flags-2-env-api-server
    spec:
      containers:
        - name: api
          image: ghcr.io/flags-2-env/flags-2-env-api-server.rs:main
          ports:
            - containerPort: 8080
          env:
            - name: FLAGS_2_ENV_API_BIND
              value: "0.0.0.0:8080"

